# Where things are
source:       .
destination:  ./_site
plugins_dir:      ./plugins
layouts_dir:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
gems: [jekyll-paginate]

#Site config
title: Title~~~
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: https://moshuqi.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 莫书旗
    email: moshuqi123@gmail.com
    imageLink: http://img0.imgtn.bdimg.com/it/u=4079873806,1394022954&fm=21&gp=0.jpg
    simpleIntro: 精通番茄炒蛋、青椒炒蛋的iOS程序员。
    detailIntro:
      <p>以下广告位长期招租 ：）</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-github-alt
    url: https://github.com/moshuqi
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: RAYWENDERLICH
      url: http://www.raywenderlich.com
    - text: objc中国
      url: http://objccn.io
    - text: OneV's Den
      url: http://www.onevcat.com/#blog
    - text: 唐巧的技术博客
      url: http://blog.devtang.com
    - text: jekyll
      url: http://jekyllrb.com
    message: Mark

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: zhanxin